apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-internal
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`100.65.51.248`) || Host(`argocd.local`)
      kind: Rule
      services:
        - name: argocd-server
          port: 443
          serversTransport: argocd-skip-tls-verify
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: skip-tls-verify
  namespace: argocd
spec:
  insecureSkipVerify: true
