apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-superuser
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-superuser
subjects:
  - kind: ServiceAccount
    name: headlamp-superuser
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: headlamp-superuser-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: headlamp-superuser
type: kubernetes.io/service-account-token
